/* tslint:disable */
/* eslint-disable */
/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Company
 */
export interface Company {
    /**
     * 証券ID
     * @type {number}
     * @memberof Company
     */
    securityId: number;
    /**
     * 従業員数
     * @type {number}
     * @memberof Company
     */
    numberOfEmployees: number | null;
    /**
     * 平均年収
     * @type {number}
     * @memberof Company
     */
    averageAnnualSalary: number | null;
    /**
     * 平均年齢
     * @type {number}
     * @memberof Company
     */
    averageAgeYears: number | null;
    /**
     * 平均勤続年数
     * @type {number}
     * @memberof Company
     */
    averageLengthOfServiceYears: number | null;
    /**
     * 銘柄コード
     * @type {number}
     * @memberof Company
     */
    securityCode: number;
    /**
     * 銘柄名
     * @type {string}
     * @memberof Company
     */
    securityName: string;
    /**
     * 市場名
     * @type {string}
     * @memberof Company
     */
    marketName: string;
    /**
     * 市場コード
     * @type {number}
     * @memberof Company
     */
    marketId: number;
    /**
     * 業種名
     * @type {string}
     * @memberof Company
     */
    industryName: string;
    /**
     * 業種コード
     * @type {number}
     * @memberof Company
     */
    industryId: number;
    /**
     * 会社名
     * @type {string}
     * @memberof Company
     */
    companyName: string;
    /**
     * 会社名(英語)
     * @type {string}
     * @memberof Company
     */
    companyNameEn: string;
    /**
     * 本店所在地
     * @type {string}
     * @memberof Company
     */
    headOfficeLocation: string;
    /**
     * 提出日
     * @type {string}
     * @memberof Company
     */
    submittedAt: string;
    /**
     * 代表者
     * @type {string}
     * @memberof Company
     */
    representative: string;
    /**
     * 事業年度の開始日
     * @type {string}
     * @memberof Company
     */
    periodStartedAt: string;
    /**
     * 事業年度の終了日
     * @type {string}
     * @memberof Company
     */
    periodEndedAt: string;
    /**
     * 事業年度の終了年
     * @type {number}
     * @memberof Company
     */
    periodEndedAtYear: number;
    /**
     * 事業年度の終了月
     * @type {number}
     * @memberof Company
     */
    periodEndedAtMonth: number;
    /**
     * 売上高(当年)
     * @type {number}
     * @memberof Company
     */
    netSales: number | null;
    /**
     * 売上高(前年)
     * @type {number}
     * @memberof Company
     */
    lastYearNetSales: number | null;
    /**
     * 営業利益(当年)
     * @type {number}
     * @memberof Company
     */
    operatingIncome: number | null;
    /**
     * 営業利益(前年)
     * @type {number}
     * @memberof Company
     */
    lastYearOperatingIncome: number | null;
    /**
     * 経常利益(当年)
     * @type {number}
     * @memberof Company
     */
    ordinaryIncome: number | null;
    /**
     * 経常利益(前年)
     * @type {number}
     * @memberof Company
     */
    lastYearOrdinaryIncome: number | null;
    /**
     * 資本金
     * @type {number}
     * @memberof Company
     */
    capitalStock: number | null;
    /**
     * 純資産
     * @type {number}
     * @memberof Company
     */
    netAssets: number | null;
    /**
     * 総資産
     * @type {number}
     * @memberof Company
     */
    totalAssets: number | null;
    /**
     * 自己資本比率
     * @type {number}
     * @memberof Company
     */
    equityToAssetRatio: number | null;
    /**
     * 自己資本利益率(ROE)
     * @type {number}
     * @memberof Company
     */
    rateOfReturnOnEquity: number | null;
    /**
     * 株価収益率(PER)
     * @type {number}
     * @memberof Company
     */
    priceEarningsRatio: number | null;
    /**
     * 営業キャッシュフロー
     * @type {number}
     * @memberof Company
     */
    netCashProvidedByUsedInOperatingActivities: number | null;
    /**
     * 投資キャッシュフロー
     * @type {number}
     * @memberof Company
     */
    netCashProvidedByUsedInInvestingActivities: number | null;
    /**
     * 財務キャッシュフロー
     * @type {number}
     * @memberof Company
     */
    netCashProvidedByUsedInFinancingActivities: number | null;
    /**
     * 現金及び現金同等物
     * @type {number}
     * @memberof Company
     */
    cashAndCashEquivalents: number | null;
    /**
     * 連結従業員数
     * @type {number}
     * @memberof Company
     */
    consolidatedNumberOfEmployees: number | null;
    /**
     * 発行済株式総数
     * @type {number}
     * @memberof Company
     */
    totalNumberOfIssuedShares: number | null;
    /**
     * 配当性向
     * @type {number}
     * @memberof Company
     */
    payoutRatio: number | null;
}

/**
 * Check if a given object implements the Company interface.
 */
export function instanceOfCompany(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "securityId" in value;
    isInstance = isInstance && "numberOfEmployees" in value;
    isInstance = isInstance && "averageAnnualSalary" in value;
    isInstance = isInstance && "averageAgeYears" in value;
    isInstance = isInstance && "averageLengthOfServiceYears" in value;
    isInstance = isInstance && "securityCode" in value;
    isInstance = isInstance && "securityName" in value;
    isInstance = isInstance && "marketName" in value;
    isInstance = isInstance && "marketId" in value;
    isInstance = isInstance && "industryName" in value;
    isInstance = isInstance && "industryId" in value;
    isInstance = isInstance && "companyName" in value;
    isInstance = isInstance && "companyNameEn" in value;
    isInstance = isInstance && "headOfficeLocation" in value;
    isInstance = isInstance && "submittedAt" in value;
    isInstance = isInstance && "representative" in value;
    isInstance = isInstance && "periodStartedAt" in value;
    isInstance = isInstance && "periodEndedAt" in value;
    isInstance = isInstance && "periodEndedAtYear" in value;
    isInstance = isInstance && "periodEndedAtMonth" in value;
    isInstance = isInstance && "netSales" in value;
    isInstance = isInstance && "lastYearNetSales" in value;
    isInstance = isInstance && "operatingIncome" in value;
    isInstance = isInstance && "lastYearOperatingIncome" in value;
    isInstance = isInstance && "ordinaryIncome" in value;
    isInstance = isInstance && "lastYearOrdinaryIncome" in value;
    isInstance = isInstance && "capitalStock" in value;
    isInstance = isInstance && "netAssets" in value;
    isInstance = isInstance && "totalAssets" in value;
    isInstance = isInstance && "equityToAssetRatio" in value;
    isInstance = isInstance && "rateOfReturnOnEquity" in value;
    isInstance = isInstance && "priceEarningsRatio" in value;
    isInstance = isInstance && "netCashProvidedByUsedInOperatingActivities" in value;
    isInstance = isInstance && "netCashProvidedByUsedInInvestingActivities" in value;
    isInstance = isInstance && "netCashProvidedByUsedInFinancingActivities" in value;
    isInstance = isInstance && "cashAndCashEquivalents" in value;
    isInstance = isInstance && "consolidatedNumberOfEmployees" in value;
    isInstance = isInstance && "totalNumberOfIssuedShares" in value;
    isInstance = isInstance && "payoutRatio" in value;

    return isInstance;
}

export function CompanyFromJSON(json: any): Company {
    return CompanyFromJSONTyped(json, false);
}

export function CompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Company {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'securityId': json['security_id'],
        'numberOfEmployees': json['number_of_employees'],
        'averageAnnualSalary': json['average_annual_salary'],
        'averageAgeYears': json['average_age_years'],
        'averageLengthOfServiceYears': json['average_length_of_service_years'],
        'securityCode': json['security_code'],
        'securityName': json['security_name'],
        'marketName': json['market_name'],
        'marketId': json['market_id'],
        'industryName': json['industry_name'],
        'industryId': json['industry_id'],
        'companyName': json['company_name'],
        'companyNameEn': json['company_name_en'],
        'headOfficeLocation': json['head_office_location'],
        'submittedAt': json['submitted_at'],
        'representative': json['representative'],
        'periodStartedAt': json['period_started_at'],
        'periodEndedAt': json['period_ended_at'],
        'periodEndedAtYear': json['period_ended_at_year'],
        'periodEndedAtMonth': json['period_ended_at_month'],
        'netSales': json['net_sales'],
        'lastYearNetSales': json['last_year_net_sales'],
        'operatingIncome': json['operating_income'],
        'lastYearOperatingIncome': json['last_year_operating_income'],
        'ordinaryIncome': json['ordinary_income'],
        'lastYearOrdinaryIncome': json['last_year_ordinary_income'],
        'capitalStock': json['capital_stock'],
        'netAssets': json['net_assets'],
        'totalAssets': json['total_assets'],
        'equityToAssetRatio': json['equity_to_asset_ratio'],
        'rateOfReturnOnEquity': json['rate_of_return_on_equity'],
        'priceEarningsRatio': json['price_earnings_ratio'],
        'netCashProvidedByUsedInOperatingActivities': json['net_cash_provided_by_used_in_operating_activities'],
        'netCashProvidedByUsedInInvestingActivities': json['net_cash_provided_by_used_in_investing_activities'],
        'netCashProvidedByUsedInFinancingActivities': json['net_cash_provided_by_used_in_financing_activities'],
        'cashAndCashEquivalents': json['cash_and_cash_equivalents'],
        'consolidatedNumberOfEmployees': json['consolidated_number_of_employees'],
        'totalNumberOfIssuedShares': json['total_number_of_issued_shares'],
        'payoutRatio': json['payout_ratio'],
    };
}

export function CompanyToJSON(value?: Company | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'security_id': value.securityId,
        'number_of_employees': value.numberOfEmployees,
        'average_annual_salary': value.averageAnnualSalary,
        'average_age_years': value.averageAgeYears,
        'average_length_of_service_years': value.averageLengthOfServiceYears,
        'security_code': value.securityCode,
        'security_name': value.securityName,
        'market_name': value.marketName,
        'market_id': value.marketId,
        'industry_name': value.industryName,
        'industry_id': value.industryId,
        'company_name': value.companyName,
        'company_name_en': value.companyNameEn,
        'head_office_location': value.headOfficeLocation,
        'submitted_at': value.submittedAt,
        'representative': value.representative,
        'period_started_at': value.periodStartedAt,
        'period_ended_at': value.periodEndedAt,
        'period_ended_at_year': value.periodEndedAtYear,
        'period_ended_at_month': value.periodEndedAtMonth,
        'net_sales': value.netSales,
        'last_year_net_sales': value.lastYearNetSales,
        'operating_income': value.operatingIncome,
        'last_year_operating_income': value.lastYearOperatingIncome,
        'ordinary_income': value.ordinaryIncome,
        'last_year_ordinary_income': value.lastYearOrdinaryIncome,
        'capital_stock': value.capitalStock,
        'net_assets': value.netAssets,
        'total_assets': value.totalAssets,
        'equity_to_asset_ratio': value.equityToAssetRatio,
        'rate_of_return_on_equity': value.rateOfReturnOnEquity,
        'price_earnings_ratio': value.priceEarningsRatio,
        'net_cash_provided_by_used_in_operating_activities': value.netCashProvidedByUsedInOperatingActivities,
        'net_cash_provided_by_used_in_investing_activities': value.netCashProvidedByUsedInInvestingActivities,
        'net_cash_provided_by_used_in_financing_activities': value.netCashProvidedByUsedInFinancingActivities,
        'cash_and_cash_equivalents': value.cashAndCashEquivalents,
        'consolidated_number_of_employees': value.consolidatedNumberOfEmployees,
        'total_number_of_issued_shares': value.totalNumberOfIssuedShares,
        'payout_ratio': value.payoutRatio,
    };
}

