/* tslint:disable */
/* eslint-disable */
/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EachCompany
 */
export interface EachCompany {
    /**
     * 
     * @type {string}
     * @memberof EachCompany
     */
    securityCode: string;
    /**
     * 
     * @type {string}
     * @memberof EachCompany
     */
    securityName: string;
    /**
     * 
     * @type {string}
     * @memberof EachCompany
     */
    securityNameEn: string;
    /**
     * 
     * @type {number}
     * @memberof EachCompany
     */
    netSales: number | null;
    /**
     * 
     * @type {number}
     * @memberof EachCompany
     */
    ordinaryIncome: number | null;
    /**
     * 
     * @type {number}
     * @memberof EachCompany
     */
    averageAnnualSalary: number | null;
    /**
     * 
     * @type {string}
     * @memberof EachCompany
     */
    industryName: string;
    /**
     * 業種コード
     * @type {number}
     * @memberof EachCompany
     */
    industryCode: number;
    /**
     * 
     * @type {string}
     * @memberof EachCompany
     */
    marketName: string;
    /**
     * 市場コード
     * @type {number}
     * @memberof EachCompany
     */
    marketId: number;
}

/**
 * Check if a given object implements the EachCompany interface.
 */
export function instanceOfEachCompany(value: object): value is EachCompany {
    if (!('securityCode' in value) || value['securityCode'] === undefined) return false;
    if (!('securityName' in value) || value['securityName'] === undefined) return false;
    if (!('securityNameEn' in value) || value['securityNameEn'] === undefined) return false;
    if (!('netSales' in value) || value['netSales'] === undefined) return false;
    if (!('ordinaryIncome' in value) || value['ordinaryIncome'] === undefined) return false;
    if (!('averageAnnualSalary' in value) || value['averageAnnualSalary'] === undefined) return false;
    if (!('industryName' in value) || value['industryName'] === undefined) return false;
    if (!('industryCode' in value) || value['industryCode'] === undefined) return false;
    if (!('marketName' in value) || value['marketName'] === undefined) return false;
    if (!('marketId' in value) || value['marketId'] === undefined) return false;
    return true;
}

export function EachCompanyFromJSON(json: any): EachCompany {
    return EachCompanyFromJSONTyped(json, false);
}

export function EachCompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): EachCompany {
    if (json == null) {
        return json;
    }
    return {
        
        'securityCode': json['security_code'],
        'securityName': json['security_name'],
        'securityNameEn': json['security_name_en'],
        'netSales': json['net_sales'],
        'ordinaryIncome': json['ordinary_income'],
        'averageAnnualSalary': json['average_annual_salary'],
        'industryName': json['industry_name'],
        'industryCode': json['industry_code'],
        'marketName': json['market_name'],
        'marketId': json['market_id'],
    };
}

export function EachCompanyToJSON(value?: EachCompany | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'security_code': value['securityCode'],
        'security_name': value['securityName'],
        'security_name_en': value['securityNameEn'],
        'net_sales': value['netSales'],
        'ordinary_income': value['ordinaryIncome'],
        'average_annual_salary': value['averageAnnualSalary'],
        'industry_name': value['industryName'],
        'industry_code': value['industryCode'],
        'market_name': value['marketName'],
        'market_id': value['marketId'],
    };
}

