/* tslint:disable */
/* eslint-disable */
/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EachIndustry
 */
export interface EachIndustry {
    /**
     * 
     * @type {number}
     * @memberof EachIndustry
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof EachIndustry
     */
    name: string;
    /**
     * 33業種コード
     * @type {number}
     * @memberof EachIndustry
     */
    code: number;
    /**
     * 業種に属する企業数
     * @type {number}
     * @memberof EachIndustry
     */
    count: number;
}

/**
 * Check if a given object implements the EachIndustry interface.
 */
export function instanceOfEachIndustry(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "count" in value;

    return isInstance;
}

export function EachIndustryFromJSON(json: any): EachIndustry {
    return EachIndustryFromJSONTyped(json, false);
}

export function EachIndustryFromJSONTyped(json: any, ignoreDiscriminator: boolean): EachIndustry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'code': json['code'],
        'count': json['count'],
    };
}

export function EachIndustryToJSON(value?: EachIndustry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'code': value.code,
        'count': value.count,
    };
}

