/* tslint:disable */
/* eslint-disable */
/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EachMarket
 */
export interface EachMarket {
    /**
     * 
     * @type {number}
     * @memberof EachMarket
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof EachMarket
     */
    name: string;
    /**
     * 市場に属する企業数
     * @type {number}
     * @memberof EachMarket
     */
    count: number;
}

/**
 * Check if a given object implements the EachMarket interface.
 */
export function instanceOfEachMarket(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "count" in value;

    return isInstance;
}

export function EachMarketFromJSON(json: any): EachMarket {
    return EachMarketFromJSONTyped(json, false);
}

export function EachMarketFromJSONTyped(json: any, ignoreDiscriminator: boolean): EachMarket {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'count': json['count'],
    };
}

export function EachMarketToJSON(value?: EachMarket | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'count': value.count,
    };
}

