/* tslint:disable */
/* eslint-disable */
/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EachIndustryCategoryIndustry } from './EachIndustryCategoryIndustry';
import {
    EachIndustryCategoryIndustryFromJSON,
    EachIndustryCategoryIndustryFromJSONTyped,
    EachIndustryCategoryIndustryToJSON,
} from './EachIndustryCategoryIndustry';

/**
 * 
 * @export
 * @interface EachIndustryCategory
 */
export interface EachIndustryCategory {
    /**
     * 
     * @type {number}
     * @memberof EachIndustryCategory
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof EachIndustryCategory
     */
    name: string;
    /**
     * 
     * @type {Array<EachIndustryCategoryIndustry>}
     * @memberof EachIndustryCategory
     */
    industries: Array<EachIndustryCategoryIndustry> | null;
}

/**
 * Check if a given object implements the EachIndustryCategory interface.
 */
export function instanceOfEachIndustryCategory(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "industries" in value;

    return isInstance;
}

export function EachIndustryCategoryFromJSON(json: any): EachIndustryCategory {
    return EachIndustryCategoryFromJSONTyped(json, false);
}

export function EachIndustryCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): EachIndustryCategory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'industries': (json['industries'] === null ? null : (json['industries'] as Array<any>).map(EachIndustryCategoryIndustryFromJSON)),
    };
}

export function EachIndustryCategoryToJSON(value?: EachIndustryCategory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'industries': (value.industries === null ? null : (value.industries as Array<any>).map(EachIndustryCategoryIndustryToJSON)),
    };
}

