/* tslint:disable */
/* eslint-disable */
/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EachIndustry
 */
export interface EachIndustry {
    /**
     * 
     * @type {number}
     * @memberof EachIndustry
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof EachIndustry
     */
    name: string;
    /**
     * 33業種コード
     * @type {number}
     * @memberof EachIndustry
     */
    code: number;
    /**
     * 業種に属する企業数
     * @type {number}
     * @memberof EachIndustry
     */
    count: number;
}

/**
 * Check if a given object implements the EachIndustry interface.
 */
export function instanceOfEachIndustry(value: object): value is EachIndustry {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function EachIndustryFromJSON(json: any): EachIndustry {
    return EachIndustryFromJSONTyped(json, false);
}

export function EachIndustryFromJSONTyped(json: any, ignoreDiscriminator: boolean): EachIndustry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'code': json['code'],
        'count': json['count'],
    };
}

export function EachIndustryToJSON(value?: EachIndustry | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
        'count': value['count'],
    };
}

