/* tslint:disable */
/* eslint-disable */
/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface FetchCompanyIds200Response
 */
export interface FetchCompanyIds200Response {
  /**
   *
   * @type {Array<number>}
   * @memberof FetchCompanyIds200Response
   */
  companyIds: Array<number>
}

/**
 * Check if a given object implements the FetchCompanyIds200Response interface.
 */
export function instanceOfFetchCompanyIds200Response(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "companyIds" in value

  return isInstance
}

export function FetchCompanyIds200ResponseFromJSON(json: any): FetchCompanyIds200Response {
  return FetchCompanyIds200ResponseFromJSONTyped(json, false)
}

export function FetchCompanyIds200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FetchCompanyIds200Response {
  if (json === undefined || json === null) {
    return json
  }
  return {
    companyIds: json["company_ids"],
  }
}

export function FetchCompanyIds200ResponseToJSON(value?: FetchCompanyIds200Response | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    company_ids: value.companyIds,
  }
}
