/* tslint:disable */
/* eslint-disable */
/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Industry
 */
export interface Industry {
    /**
     * 
     * @type {number}
     * @memberof Industry
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Industry
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Industry
     */
    code: number;
}

/**
 * Check if a given object implements the Industry interface.
 */
export function instanceOfIndustry(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function IndustryFromJSON(json: any): Industry {
    return IndustryFromJSONTyped(json, false);
}

export function IndustryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Industry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'code': json['code'],
    };
}

export function IndustryToJSON(value?: Industry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'code': value.code,
    };
}

