/* tslint:disable */
/* eslint-disable */
/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface Market
 */
export interface Market {
  /**
   *
   * @type {number}
   * @memberof Market
   */
  id: number
  /**
   *
   * @type {string}
   * @memberof Market
   */
  name: string
}

/**
 * Check if a given object implements the Market interface.
 */
export function instanceOfMarket(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "id" in value
  isInstance = isInstance && "name" in value

  return isInstance
}

export function MarketFromJSON(json: any): Market {
  return MarketFromJSONTyped(json, false)
}

export function MarketFromJSONTyped(json: any, ignoreDiscriminator: boolean): Market {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json["id"],
    name: json["name"],
  }
}

export function MarketToJSON(value?: Market | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    name: value.name,
  }
}
