/* tslint:disable */
/* eslint-disable */
/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Market } from './Market';
import {
    MarketFromJSON,
    MarketFromJSONTyped,
    MarketToJSON,
} from './Market';

/**
 * 
 * @export
 * @interface ResponseMarket
 */
export interface ResponseMarket {
    /**
     * 
     * @type {Market}
     * @memberof ResponseMarket
     */
    market: Market;
}

/**
 * Check if a given object implements the ResponseMarket interface.
 */
export function instanceOfResponseMarket(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "market" in value;

    return isInstance;
}

export function ResponseMarketFromJSON(json: any): ResponseMarket {
    return ResponseMarketFromJSONTyped(json, false);
}

export function ResponseMarketFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseMarket {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'market': MarketFromJSON(json['market']),
    };
}

export function ResponseMarketToJSON(value?: ResponseMarket | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'market': MarketToJSON(value.market),
    };
}

