/* tslint:disable */
/* eslint-disable */
/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Industry } from './Industry';
import {
    IndustryFromJSON,
    IndustryFromJSONTyped,
    IndustryToJSON,
} from './Industry';

/**
 * 
 * @export
 * @interface ResponseIndustry
 */
export interface ResponseIndustry {
    /**
     * 
     * @type {Industry}
     * @memberof ResponseIndustry
     */
    industry: Industry;
}

/**
 * Check if a given object implements the ResponseIndustry interface.
 */
export function instanceOfResponseIndustry(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "industry" in value;

    return isInstance;
}

export function ResponseIndustryFromJSON(json: any): ResponseIndustry {
    return ResponseIndustryFromJSONTyped(json, false);
}

export function ResponseIndustryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseIndustry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'industry': IndustryFromJSON(json['industry']),
    };
}

export function ResponseIndustryToJSON(value?: ResponseIndustry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'industry': IndustryToJSON(value.industry),
    };
}

