/* tslint:disable */
/* eslint-disable */
/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface ResponseIndustryIDs
 */
export interface ResponseIndustryIDs {
  /**
   *
   * @type {Array<number>}
   * @memberof ResponseIndustryIDs
   */
  industryIds: Array<number>
}

/**
 * Check if a given object implements the ResponseIndustryIDs interface.
 */
export function instanceOfResponseIndustryIDs(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "industryIds" in value

  return isInstance
}

export function ResponseIndustryIDsFromJSON(json: any): ResponseIndustryIDs {
  return ResponseIndustryIDsFromJSONTyped(json, false)
}

export function ResponseIndustryIDsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResponseIndustryIDs {
  if (json === undefined || json === null) {
    return json
  }
  return {
    industryIds: json["industry_ids"],
  }
}

export function ResponseIndustryIDsToJSON(value?: ResponseIndustryIDs | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    industry_ids: value.industryIds,
  }
}
