/* tslint:disable */
/* eslint-disable */
/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseMarketIDs
 */
export interface ResponseMarketIDs {
    /**
     * 
     * @type {Array<number>}
     * @memberof ResponseMarketIDs
     */
    marketIds: Array<number>;
}

/**
 * Check if a given object implements the ResponseMarketIDs interface.
 */
export function instanceOfResponseMarketIDs(value: object): value is ResponseMarketIDs {
    if (!('marketIds' in value) || value['marketIds'] === undefined) return false;
    return true;
}

export function ResponseMarketIDsFromJSON(json: any): ResponseMarketIDs {
    return ResponseMarketIDsFromJSONTyped(json, false);
}

export function ResponseMarketIDsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseMarketIDs {
    if (json == null) {
        return json;
    }
    return {
        
        'marketIds': json['market_ids'],
    };
}

export function ResponseMarketIDsToJSON(value?: ResponseMarketIDs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'market_ids': value['marketIds'],
    };
}

