/* tslint:disable */
/* eslint-disable */
/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseSecurityCodes
 */
export interface ResponseSecurityCodes {
    /**
     * 
     * @type {Array<string>}
     * @memberof ResponseSecurityCodes
     */
    securityCodes: Array<string>;
}

/**
 * Check if a given object implements the ResponseSecurityCodes interface.
 */
export function instanceOfResponseSecurityCodes(value: object): value is ResponseSecurityCodes {
    if (!('securityCodes' in value) || value['securityCodes'] === undefined) return false;
    return true;
}

export function ResponseSecurityCodesFromJSON(json: any): ResponseSecurityCodes {
    return ResponseSecurityCodesFromJSONTyped(json, false);
}

export function ResponseSecurityCodesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseSecurityCodes {
    if (json == null) {
        return json;
    }
    return {
        
        'securityCodes': json['security_codes'],
    };
}

export function ResponseSecurityCodesToJSON(value?: ResponseSecurityCodes | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'security_codes': value['securityCodes'],
    };
}

