/* tslint:disable */
/* eslint-disable */
/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseCompanyIDs
 */
export interface ResponseCompanyIDs {
    /**
     * 
     * @type {Array<number>}
     * @memberof ResponseCompanyIDs
     */
    companyIds: Array<number>;
}

/**
 * Check if a given object implements the ResponseCompanyIDs interface.
 */
export function instanceOfResponseCompanyIDs(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "companyIds" in value;

    return isInstance;
}

export function ResponseCompanyIDsFromJSON(json: any): ResponseCompanyIDs {
    return ResponseCompanyIDsFromJSONTyped(json, false);
}

export function ResponseCompanyIDsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseCompanyIDs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'companyIds': json['company_ids'],
    };
}

export function ResponseCompanyIDsToJSON(value?: ResponseCompanyIDs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'company_ids': value.companyIds,
    };
}

