steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/company-ranking-job:$COMMIT_SHA', '-f', 'ruby/Dockerfile.prod', '.']
  # push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/company-ranking-job:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'jobs'
    - 'deploy'
    - 'company-ranking-job'
    - '--image'
    - 'gcr.io/$PROJECT_ID/company-ranking-job:$COMMIT_SHA'
    - '--region'
    - 'asia-northeast1'
images:
- 'gcr.io/$PROJECT_ID/company-ranking-job:$COMMIT_SHA'
