version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "./ruby"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "rails"
    groups:
      ruby-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "./typescript"
    schedule:
      interval: "monthly"
    groups:
      typescript-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "./go"
    schedule:
      interval: "monthly"
    groups:
      go-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "./.github/workflows"
    schedule:
      interval: "monthly"
