version: 2
updates:
  - package-ecosystem: "npm"
    directory: "./front"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "sass-loader"
      - dependency-name: "css-loader"
  - package-ecosystem: "bundler"
    directory: "./ruby"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "rails"
  - package-ecosystem: "npm"
    directory: "./typescript"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "./go"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "./.github/workflows"
    schedule:
      interval: "monthly"
