version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "./ruby"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "rails"
      - dependency-name: "nokogiri"
    groups:
      ruby-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "./typescript"
    schedule:
      interval: "monthly"
    groups:
      javascript-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "./go"
    schedule:
      interval: "monthly"
    groups:
      go-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "./go/tools"
    schedule:
      interval: "monthly"
    groups:
      go-tools-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "./.github/workflows"
    schedule:
      interval: "monthly"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directory: "./terraform/prod"
    schedule:
      interval: monthly
    groups:
      terraform-dependencies:
        patterns:
          - "*"
