version: '3.8'

services:
  db:
    image: postgres:12.7-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./ruby/tmp/db:/var/lib/postgresql/data
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
  ruby:
    build:
      context: ./ruby
      args:
        WORKDIR: $WORKDIR
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
    volumes:
      - ./ruby:/$WORKDIR
    depends_on:
      - db
    command: /bin/sh -c "echo rails api is not used."
  go: # use hot reload tool like air
    build:
      context: ./go
    environment:
      FRONT_URL: $FRONT_URL
      ENV: development
      DATABASE_URL: "postgres://postgres:password@db:5432/myapp_development?sslmode=disable"
      PORT: $API_HOST_PORT
    volumes:
      - ./go:/go/src
    depends_on:
      - db
    ports:
      - "$API_HOST_PORT:$API_HOST_PORT"
  front:
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        API_URL: "http://localhost:$API_HOST_PORT"
    command: yarn run dev
    volumes:
      - ./front:/$WORKDIR
    ports:
      - "$FRONT_HOST_PORT:$CONTAINER_PORT"
    depends_on:
      - ruby
      - go
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./openapi:/usr/share/nginx/html/openapi
    ports:
      # NOTE: ホストからは8000で接続する
      - 8000:8080
