version: '3.8'

services:
  db:
    image: postgres:12.7-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./ruby/tmp/db:/var/lib/postgresql/data
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
  ruby:
    build:
      context: ./ruby
      args:
        WORKDIR: $WORKDIR
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL
    volumes:
      - ./ruby:/$WORKDIR
      - bundle_cache:/$WORKDIR/vendor/bundle
    depends_on:
      - db
    command: /bin/sh -c "echo rails api is not used."
  go:
    build:
      context: ./go
    environment:
      FRONT_URL: $FRONT_URL
      ENV: development
      PORT: $API_HOST_PORT
      GOBIN: /go/src/bin
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      DATABASE_HOST_URL: $DATABASE_HOST_URL
      DATABASE_URL: $DATABASE_URL
      POSTGRES_TEST_NAME: $POSTGRES_TEST_NAME
      POSTGRES_TEST_USER: $POSTGRES_TEST_USER
      DATABASE_TEST_URL: $DATABASE_TEST_URL
    command: air
    volumes:
      - ./go:/go/src
    depends_on:
      - db
    ports:
      - "$API_HOST_PORT:$API_HOST_PORT"
  typescript:
    build:
      context: ./typescript
      args:
        WORKDIR: $WORKDIR
    environment:
      WATCHPACK_POLLING: true
      PORT: $FRONT_HOST_PORT
      NEXT_PUBLIC_API_URL: $NEXT_PUBLIC_DOCKER_API_URL
      NEXT_PUBLIC_TWITTER_ID: $NEXT_PUBLIC_TWITTER_ID
    command: npm run dev
    volumes:
      - ./typescript:/$WORKDIR
      - /$WORKDIR/node_modules
    ports:
      - "$FRONT_HOST_PORT:$FRONT_HOST_PORT"
    depends_on:
      - db
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./openapi:/usr/share/nginx/html/doc
    ports:
      # NOTE: ホストからは8000で接続する
      - 8000:8080
    environment:
      API_URL: doc/openapi.yaml
volumes:
  go_src_bin:
  bundle_cache:
