[build]
  base = "front/"
  publish = "dist/"
[build.environment]
  YARN_VERSION = "1.22.5"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_VERSION = "14.17.3"
  API_URL = "https://company-ranking.herokuapp.com"
  GOOGLE_ANALYTICS_ID = "UA-118701335-5"
