openapi: "3.1.3"
info:
  title: Company Search API Document
  version: 1.0.0
paths:
  /api/v1/companies/{code}:
    get:
      operationId: fetchCompany
      summary: Get Company
      parameters:
        - in: path
          name: code
          required: true
          schema:
            type: integer
      responses:
        200:
          description: get Company
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseCompany"
components:
  schemas:
    responseCompany:
      type: object
      required:
        - company
      properties:
        company:
          $ref: "#/components/schemas/Company"
    Company:
      type: object
      required:
        - security_id
        - number_of_employees
        - average_annual_salary
        - average_age_years
        - average_length_of_service_years
        - security_code
        - security_name
        - market_name
        - market_id
        - industry_name
        - industry_id
        - company_name
        - company_name_en
        - head_office_location
        - submitted_at
        - representative
        - period_started_at
        - period_ended_at
        - period_ended_at_year
        - period_ended_at_month
        - net_sales
        - last_year_net_sales
        - operating_income
        - last_year_operating_income
        - ordinary_income
        - last_year_ordinary_income
        - capital_stock
        - net_assets
        - total_assets
        - equity_to_asset_ratio
        - rate_of_return_on_equity
        - price_earnings_ratio
        - net_cash_provided_by_used_in_operating_activities
        - net_cash_provided_by_used_in_investing_activities
        - net_cash_provided_by_used_in_financing_activities
        - cash_and_cash_equivalents
        - consolidated_number_of_employees
      properties:
        security_id:
          type: number
        # 従業員情報
        number_of_employees:
          type: number
          nullable: true
        average_annual_salary:
          type: number
          nullable: true
          description: 1万で割った値
        average_age_years:
          type: number
          format: float
          nullable: true
        average_length_of_service_years:
          type: number
          format: float
          nullable: true
        # 基本情報
        security_code:
          type: number
        security_name:
          type: string
        market_name:
          type: string
        market_id:
          type: number
        industry_name:
          type: string
        industry_id:
          type: number
        company_name:
          type: string
        company_name_en:
          type: string
        head_office_location:
          type: string
        representative:
          type: string
        # 決算情報
        period_started_at:
          type: string
          example: 2020年4月1日
        period_ended_at:
          type: string
          example: 2021年3月31日
        period_ended_at_year:
          type: integer
          example: 2021
        period_ended_at_month:
          type: integer
          example: 3
        net_sales:
          type: number
          nullable: true
          description: 1億で割った値
        last_year_net_sales:
          type: number
          nullable: true
          description: 1億で割った値
        operating_income:
          type: number
          nullable: true
          description: 1億で割った値
        last_year_operating_income:
          type: number
          nullable: true
          description: 1億で割った値
        ordinary_income:
          type: number
          nullable: true
          description: 1億で割った値
        last_year_ordinary_income:
          type: number
          nullable: true
          description: 1億で割った値
        capital_stock:
          type: number
          nullable: true
        net_assets:
          type: number
          nullable: true
          description: 純資産
        total_assets:
          type: number
          nullable: true
          description: 総資産
        equity_to_asset_ratio:
          type: number
          nullable: true
          description: 自己資本比率
        rate_of_return_on_equity:
          type: number
          nullable: true
          description: 自己資本利益率(ROE)
        price_earnings_ratio:
          type: number
          nullable: true
          description: 株価収益率(PER)
        net_cash_provided_by_used_in_operating_activities:
          type: number
          nullable: true
        net_cash_provided_by_used_in_investing_activities:
          type: number
          nullable: true
        net_cash_provided_by_used_in_financing_activities:
          type: number
          nullable: true
        cash_and_cash_equivalents:
          type: number
          nullable: true
        consolidated_number_of_employees:
          type: number
          nullable: true
