openapi: 3.0.3
info:
  title: Company Search API Document
  version: 1.0.0
paths:
  /api/v1/companies:
    get:
      operationId: fetchCompanies
      summary: Get and Search Companies
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: sort_type
          required: true
          schema:
            type: string
            enum:
              - net_sales
              - average_annual_salary
        - in: query
          name: q
          description: query for company_name or security_id
          schema:
            type: string
      responses:
        200:
          description: get Companies
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseCompanies"
  /api/v1/companies/{id}:
    get:
      operationId: fetchCompany
      summary: Get Company
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: get Company
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseCompany"
  /api/v1/industries:
    get:
      operationId: fetchIndustries
      summary: Get Industries
      responses:
        200:
          description: get Industries
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseIndustries"
  /api/v1/industries/{id}:
    get:
      operationId: fetchIndustry
      summary: Get Industry
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: get Industry
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseIndustry"
  /api/v1/markets:
    get:
      operationId: fetchMarkets
      summary: Get Markets
      responses:
        200:
          description: get Markets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseMarkets"
  /api/v1/markets/{id}:
    get:
      operationId: fetchMarket
      summary: Get Market
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: get Market
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseMarket"
  /api/v1/company_ids:
    get:
      operationId: fetchCompanyIds
      summary: Get CompanyIds
      responses:
        200:
          description: get CompanyIds
          content:
            application/json:
              schema:
                type: object
                required:
                  - company_ids
                properties:
                  company_ids:
                    type: array
                    items:
                      type: integer
  /api/v1/industry_ids:
    get:
      operationId: fetchIndustryIds
      summary: Get IndustryIds
      responses:
        200:
          description: get IndustryIds
          content:
            application/json:
              schema:
                type: object
                required:
                  - industry_ids
                properties:
                  industry_ids:
                    type: array
                    items:
                      type: integer
components:
  schemas:
    responseCompanies:
      type: object
      required:
        - meta
        - companies
      properties:
        meta:
          $ref: "#/components/schemas/meta"
        companies:
          type: array
          items:
            $ref: "#/components/schemas/eachCompany"
    eachCompany:
      type: object
      required:
        - security_id
        - security_name
        - average_annual_salary
        - net_sales
        - ordinary_income
      properties:
        security_id:
          type: number
        security_name:
          type: string
        average_annual_salary:
          type: number
          nullable: true
          description: 1万で割った値
        net_sales:
          type: number
          nullable: true
          description: 1億で割った値
        ordinary_income:
          type: number
          nullable: true
          description: 1億で割った値
    responseCompany:
      type: object
      required:
        - company
      properties:
        company:
          $ref: "#/components/schemas/Company"
    Company:
      type: object
      required:
        - security_id
        - number_of_employees
        - average_annual_salary
        - average_age_years
        - average_length_of_service_years
        - security_code
        - security_name
        - market_name
        - market_id
        - industry_name
        - industry_id
        - company_name
        - company_name_en
        - head_office_location
        - submitted_at
        - representative
        - period_started_at
        - period_ended_at
        - net_sales
        - last_year_net_sales
        - operating_income
        - last_year_operating_income
        - ordinary_income
        - last_year_ordinary_income
      properties:
        security_id:
          type: number
        # 従業員情報
        number_of_employees:
          type: number
          nullable: true
        average_annual_salary:
          type: number
          nullable: true
          description: 1万で割った値
        average_age_years:
          type: number
          format: float
          nullable: true
        average_length_of_service_years:
          type: number
          format: float
          nullable: true
        # 基本情報
        security_code:
          type: number
        security_name:
          type: string
        market_name:
          type: string
        market_id:
          type: number
        industry_name:
          type: string
        industry_id:
          type: number
        company_name:
          type: string
        company_name_en:
          type: string
        head_office_location:
          type: string
        representative:
          type: string
        # 決算情報
        period_started_at:
          type: string
          example: 2020年4月1日
        period_ended_at:
          type: string
          example: 2021年3月31日
        net_sales:
          type: number
          nullable: true
          description: 1億で割った値
        last_year_net_sales:
          type: number
          nullable: true
          description: 1億で割った値
        operating_income:
          type: number
          nullable: true
          description: 1億で割った値
        last_year_operating_income:
          type: number
          nullable: true
          description: 1億で割った値
        ordinary_income:
          type: number
          nullable: true
          description: 1億で割った値
        last_year_ordinary_income:
          type: number
          nullable: true
          description: 1億で割った値
    responseIndustries:
      type: object
      required:
        - industry_categories
      properties:
        industry_categories:
          type: array
          items:
            $ref: "#/components/schemas/eachIndustryCategory"
    eachIndustryCategory:
      type: object
      required:
        - id
        - name
        - industries
      properties:
        id:
          type: integer
        name:
          type: string
        industries:
          type: array
          nullable: true
          items:
            type: object
            required:
              - id
              - name
              - code
              - count
            properties:
              id:
                type: integer
              name:
                type: string
              code:
                type: integer
                description: 33業種コード
              count:
                type: integer
                description: 業種に属する企業数
    responseIndustry:
      type: object
      required:
        - industry
      properties:
        industry:
          $ref: "#/components/schemas/industry"
    industry:
      type: object
      required:
        - id
        - name
        - code
      properties:
        id:
          type: number
        name:
          type: string
        code:
          type: number
    responseMarkets:
      type: object
      required:
        - markets
      properties:
        markets:
          type: array
          items:
            $ref: "#/components/schemas/eachMarket"
    eachMarket:
      type: object
      required:
        - id
        - name
        - count
      properties:
        id:
          type: integer
        name:
          type: string
        count:
          type: integer
          description: 市場に属する企業数
    responseMarket:
      type: object
      required:
        - market
      properties:
        market:
          $ref: "#/components/schemas/market"
    market:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
    meta:
      type: object
      required:
        - from
        - count
        - items
        - page
        - pages
        - prev
        - next
      properties:
        from:
          type: number
          description: アイテムの取得開始位置
        count:
          type: number
          description: 総アイテム数
        items:
          type: number
          description: 1ページあたりのアイテム数
        page:
          type: number
          description: 現在のページ番号
        pages:
          type: number
          description: 最後ののページ番号
        prev:
          type: number
          nullable: true
          description: 前のページ番号
        next:
          type: number
          nullable: true
          description: 次のページ番号
