export default {
  id: 6647,
  code: 6467,
  name: 'ニチダイ',
  segment_name: 'JASDAQ',
  industry_name: '機械',
  period_started_at: '2020年4月1日',
  period_ended_at: '2021年3月31日',
  company_name: '株式会社ニチダイ',
  company_name_en: 'NICHIDAI CORPORATION',
  head_office_location: '京都府京田辺市薪北町田13番地',
  submitted_at: '2021年6月26日',
  representative: '代表取締役社長執行役員    伊藤　直紀',
  number_of_employees: 374,
  average_age_years: 39.3,
  average_length_of_service_years: 14.7,
  average_annual_salary: '512',
  net_sales: '10,823百万円',
  last_year_net_sales: '14,774百万円',
  operating_income: '-',
  last_year_operating_income: '-',
  last_year_ordinary_income: '743百万円',
  ordinary_income: '-173百万円'
}
