/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Company {
    security_id: number;
    number_of_employees: number | null;
    /**
     * 1万で割った値
     */
    average_annual_salary: number | null;
    average_age_years: number | null;
    average_length_of_service_years: number | null;
    security_code: number;
    security_name: string;
    market_name: string;
    market_id: number;
    industry_name: string;
    industry_id: number;
    company_name: string;
    company_name_en: string;
    head_office_location: string;
    representative: string;
    period_started_at: string;
    period_ended_at: string;
    period_ended_at_year: number;
    period_ended_at_month: number;
    /**
     * 1億で割った値
     */
    net_sales: number | null;
    /**
     * 1億で割った値
     */
    last_year_net_sales: number | null;
    /**
     * 1億で割った値
     */
    operating_income: number | null;
    /**
     * 1億で割った値
     */
    last_year_operating_income: number | null;
    /**
     * 1億で割った値
     */
    ordinary_income: number | null;
    /**
     * 1億で割った値
     */
    last_year_ordinary_income: number | null;
    capital_stock: number | null;
    /**
     * 純資産
     */
    net_assets: number | null;
    /**
     * 総資産
     */
    total_assets: number | null;
    /**
     * 自己資本比率
     */
    equity_to_asset_ratio: number | null;
    /**
     * 自己資本利益率(ROE)
     */
    rate_of_return_on_equity: number | null;
    /**
     * 株価収益率(PER)
     */
    price_earnings_ratio: number | null;
    net_cash_provided_by_used_in_operating_activities: number | null;
    net_cash_provided_by_used_in_investing_activitie: number | null;
    net_cash_provided_by_used_in_financing_activities: number | null;
    cash_and_cash_equivalents: number | null;
    consolidated_number_of_employees: number | null;
}
