/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Company {
    security_id: number;
    number_of_employees: number | null;
    /**
     * 1万で割った値
     */
    average_annual_salary: number | null;
    average_age_years: number | null;
    average_length_of_service_years: number | null;
    security_code: number;
    security_name: string;
    market_name: string;
    market_id: number;
    industry_name: string;
    industry_id: number;
    company_name: string;
    company_name_en: string;
    head_office_location: string;
    representative: string;
    period_started_at: string;
    period_ended_at: string;
    /**
     * 1億で割った値
     */
    net_sales: number | null;
    /**
     * 1億で割った値
     */
    last_year_net_sales: number | null;
    /**
     * 1億で割った値
     */
    operating_income: number | null;
    /**
     * 1億で割った値
     */
    last_year_operating_income: number | null;
    /**
     * 1億で割った値
     */
    ordinary_income: number | null;
    /**
     * 1億で割った値
     */
    last_year_ordinary_income: number | null;
}
