/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Meta {
    /**
     * アイテムの取得開始位置
     */
    from: number;
    /**
     * 総アイテム数
     */
    count: number;
    /**
     * 1ページあたりのアイテム数
     */
    items: number;
    /**
     * 現在のページ番号
     */
    page: number;
    /**
     * 最後ののページ番号
     */
    pages: number;
    /**
     * 前のページ番号
     */
    prev: number | null;
    /**
     * 次のページ番号
     */
    next: number | null;
}
