-- Generated by xo for the public schema.

-- table ar_internal_metadata
CREATE TABLE ar_internal_metadata (
  key VARCHAR NOT NULL,
  value VARCHAR,
  created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
  updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
  PRIMARY KEY (key)
);

-- table industries
CREATE TABLE industries (
  id BIGSERIAL,
  name VARCHAR NOT NULL,
  code INTEGER NOT NULL,
  created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
  updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
  industry_category_id BIGINT,
  UNIQUE (code),
  UNIQUE (name),
  PRIMARY KEY (id)
);

-- index index_industries_on_industry_category_id
CREATE INDEX index_industries_on_industry_category_id ON industries (industry_category_id);

-- table securities
CREATE TABLE securities (
  id BIGSERIAL,
  code INTEGER NOT NULL,
  name VARCHAR NOT NULL,
  market_id BIGINT NOT NULL,
  industry_code INTEGER NOT NULL REFERENCES industries (code),
  created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
  updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
  UNIQUE (code),
  UNIQUE (name),
  PRIMARY KEY (id)
);

-- index index_securities_on_industry_code
CREATE INDEX index_securities_on_industry_code ON securities (industry_code);

-- index index_securities_on_market_id
CREATE INDEX index_securities_on_market_id ON securities (market_id);

-- table documents
CREATE TABLE documents (
  id BIGSERIAL,
  security_code INTEGER NOT NULL REFERENCES securities (code),
  document_id VARCHAR NOT NULL,
  edinet_code VARCHAR NOT NULL,
  filer_name VARCHAR NOT NULL,
  period_started_at DATE NOT NULL,
  period_ended_at DATE NOT NULL,
  details_searched_at TIMESTAMP,
  company_name VARCHAR,
  company_name_en VARCHAR,
  head_office_location VARCHAR,
  submitted_at DATE,
  fiscal_year VARCHAR,
  representative VARCHAR,
  number_of_employees INTEGER,
  average_age_years DOUBLE PRECISION,
  average_length_of_service_years DOUBLE PRECISION,
  average_annual_salary BIGINT,
  last_year_net_sales BIGINT,
  net_sales BIGINT,
  last_year_operating_income BIGINT,
  operating_income BIGINT,
  last_year_ordinary_income BIGINT,
  ordinary_income BIGINT,
  created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
  updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
  capital_stock BIGINT,
  net_assets BIGINT,
  total_assets BIGINT,
  equity_to_asset_ratio DOUBLE PRECISION,
  rate_of_return_on_equity DOUBLE PRECISION,
  price_earnings_ratio DOUBLE PRECISION,
  net_cash_provided_by_used_in_operating_activities BIGINT,
  net_cash_provided_by_used_in_investing_activities BIGINT,
  net_cash_provided_by_used_in_financing_activities BIGINT,
  cash_and_cash_equivalents BIGINT,
  consolidated_number_of_employees INTEGER,
  total_number_of_issued_shares BIGINT,
  payout_ratio DOUBLE PRECISION,
  PRIMARY KEY (id),
  UNIQUE (document_id)
);

-- index index_documents_on_security_code
CREATE INDEX index_documents_on_security_code ON documents (security_code);

-- table industry_categories
CREATE TABLE industry_categories (
  id BIGSERIAL,
  name VARCHAR NOT NULL,
  created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
  updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
  UNIQUE (name),
  PRIMARY KEY (id)
);

-- table markets
CREATE TABLE markets (
  id BIGSERIAL,
  name VARCHAR NOT NULL,
  created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
  updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
  UNIQUE (name),
  PRIMARY KEY (id)
);

-- table schema_migrations
CREATE TABLE schema_migrations (
  version VARCHAR NOT NULL,
  PRIMARY KEY (version)
);

-- table security_lists
CREATE TABLE security_lists (
  id BIGSERIAL,
  file_title VARCHAR NOT NULL,
  downloaded_at DATE NOT NULL,
  created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
  updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
  UNIQUE (file_title),
  PRIMARY KEY (id)
);
