name: Go package

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go/go.mod
          cache: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
