name: ESLint
on: [push]
jobs:
  nuxt-lint:
    name: Run eslint for nuxt.js
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        run: yarn install
      - name: eslint review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: './**/*.{vue,ts,js}'
      - name: Run eslint
        run: yarn lint
  next-lint:
    name: Run eslint for next.js
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
          - name: Install dependencies
            run: npm ci
          - name: Run lint check
            run: npm run lint
          - name: Reviewdog
            uses: reviewdog/action-eslint@v1
