name: ESLint
on: [push]
jobs:
  next-lint:
    name: Run eslint for next.js
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
          - name: Install dependencies
            run: npm ci
          - name: Run lint check
            run: npm run lint
          - name: Reviewdog
            uses: reviewdog/action-eslint@v1
