name: Prettier
on: [push]
jobs:
  next-lint:
    name: Run prettier for next.js
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Run format code
        run: npm run format
      - name: Check diff exists
        run: |
          git add -N .
          git diff
          line=`git diff | wc -l`
          if [ $line -gt 0 ]; then
            echo "You need to format"
            git diff
            exit -1
          fi
