name: RuboCop
on: [push]
jobs:
  rubocop:
    name: Run rubocop
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ruby
    env:
      RAILS_ENV: test
      FRONT_DOMAIN: dummy
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
          bundler-cache: true
          working-directory: ./ruby
      - name: Run rubocop
        run: bundle exec rubocop
