name: Yarn upgrade
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.17.3
    - uses: browniebroke/yarn-upgrade-action@v1
      with:
        working-directory: ./front
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update/yarn-upgrade
        title: Run yarn upgrade
        commit-message: Run yarn upgrade
