/* tslint:disable */
/* eslint-disable */
/**
 * Company Search API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Company } from './Company';
import {
    CompanyFromJSON,
    CompanyFromJSONTyped,
    CompanyToJSON,
} from './Company';

/**
 * 
 * @export
 * @interface ResponseCompany
 */
export interface ResponseCompany {
    /**
     * 
     * @type {Company}
     * @memberof ResponseCompany
     */
    company: Company;
}

/**
 * Check if a given object implements the ResponseCompany interface.
 */
export function instanceOfResponseCompany(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "company" in value;

    return isInstance;
}

export function ResponseCompanyFromJSON(json: any): ResponseCompany {
    return ResponseCompanyFromJSONTyped(json, false);
}

export function ResponseCompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseCompany {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'company': CompanyFromJSON(json['company']),
    };
}

export function ResponseCompanyToJSON(value?: ResponseCompany | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'company': CompanyToJSON(value.company),
    };
}

